import { ref, computed } from 'vue';

export type LanguageCode = 'en' | 'fr' | 'de' | 'it' | 'es';

export interface LanguageOption {
  code: LanguageCode;
  label: string;
  flag: string;
  nativeName: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', flag: '🇬🇧', nativeName: 'English' },
  { code: 'fr', label: 'French', flag: '🇫🇷', nativeName: 'Français' },
  { code: 'de', label: 'German', flag: '🇩🇪', nativeName: 'Deutsch' },
  { code: 'it', label: 'Italian', flag: '🇮🇹', nativeName: 'Italiano' },
  { code: 'es', label: 'Spanish', flag: '🇪🇸', nativeName: 'Español' },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Brand & System
    'brand.name': 'CP PRO MAX',
    'brand.subtitle': '3D Diagnostix Cloud ERP & Co-Diagnostix Suite',
    'brand.version': 'v4.2 Max Pro',
    
    // Navigation Target Pages
    'nav.dashboard': 'Dashboard',
    'nav.flow': 'Master Orders Flow',
    'nav.addCase': 'Add New Case',
    'nav.orderDetails': 'Order Details',
    'nav.quarterTargets': 'Quarter Targets',
    'nav.task47': 'Task 47: Models',
    'nav.task31': 'Task 31: Staff Targets',
    'nav.editCase': 'Edit Case',
    'nav.profile': 'Operator Profile & Settings',
    
    // Master Table Columns (Image 1 Exact)
    'col.serial': '# tl',
    'col.scanCenter': 'Scan Center tl',
    'col.doctor': 'Doctor tl',
    'col.patientName': 'Patient Name tl',
    'col.isLocked': 'Is Locked (?)',
    'col.notes': 'Notes',
    'col.archiveDate': 'Archive Date',
    'col.more': '...',
    'col.order': 'Order',
    'col.billTo': 'Bill To',
    'col.max': 'Max.',
    'col.mand': 'Mand.',
    'col.format': 'Format',
    'col.amountBilled': 'Amount Billed',
    'col.vouchers': 'Vouchers',
    'col.receivedTime': 'Received Time',
    'col.sentTime': 'Sent Time',
    'col.updateTime': 'Update Time',
    'col.chargedOn': 'Charged On',
    'col.action': 'Action',
    'col.changeRequest': 'Change Request',
    'col.csTask': 'CS-Task',

    // Actions & Common
    'action.newCase': 'New Case',
    'action.search': 'Quick Search cases, doctors, scans...',
    'action.dockTop': 'Top Navbar',
    'action.dockBottom': 'Bottom Dock',
    'action.dockLeft': 'Left Sidebar',
    'action.dockRight': 'Right Sidebar',
    'action.dragHandle': 'Drag to dock at any edge (Top / Left / Right / Bottom)',
    'action.selectAll': 'Select All',
    'action.clearAll': 'Clear All',
    'action.filter': 'Filter',
    'action.export': 'Export',
    'action.print': 'Print Report',
    'action.save': 'Save Changes',
    'action.cancel': 'Cancel',
    'action.status': 'Status',
    'action.priority': 'Priority',
    'action.actions': 'Actions',
    'action.view': 'View',
    'action.edit': 'Edit',
    
    // UI States
    'state.normal': 'Normal Live',
    'state.loading': 'Loading Status',
    'state.empty': 'Empty Status',
    'state.error': 'Error Status',
    'state.tester': 'UI States Showcase',

    // Power BI & Quarter Targets
    'powerbi.hub': 'Power BI Analytics',
    'powerbi.cadQueue': 'CAD Production Queue',
    'powerbi.refresh': 'Refresh Power BI Metrics',
    'powerbi.targetAttainment': 'Q4 Target Attainment',
    'powerbi.surgicalGuides': 'Surgical Guides (SG)',
    'powerbi.treatmentPlans': 'Co-Dx Plans (TP)',
    'powerbi.avgTurnaround': 'Avg. Turnaround Time',
    'powerbi.actualRevenue': 'Actual Revenue',
    'powerbi.targetQuota': 'Target Quota',
    'powerbi.serviceShare': 'Service Line Share',
    'powerbi.regionalHubs': 'Regional Diagnostic Hubs Attainment',
    'report.quarterTargets': '3DDX Quarter Targets & Performance Viewer',
    'report.totalCases': 'TOTAL CASES PRODUCED',
    'report.grossRevenue': 'QUARTERLY GROSS REVENUE',
    'report.guidesPrinted': 'SURGICAL GUIDES PRINTED',
    'report.turnaround': 'AVERAGE LAB TURNAROUND',
    'report.targetVsAchieved': 'Target vs. Achieved Production (Q1 - Q4)',
    'report.monthlyRunRate': 'Monthly Run Rate & Target Envelope',

    // Teeth Chart
    'teeth.upper': '+ Upper (1-16)',
    'teeth.lower': '+ Lower (17-32)',
    'teeth.smile': 'Smile Zone',
    'teeth.posteriors': '+ Posteriors',
    'teeth.clearAll': 'Clear All',
    'teeth.activeTool': 'Active Tool:',
    'teeth.crown': 'Crown',
    'teeth.bridge': 'Bridge Unit',
    'teeth.veneer': 'Veneer',
    'teeth.implant': 'Implant',
    'teeth.inlay': 'Inlay / Onlay',
    'teeth.missing': 'Missing / Pontic',

    // Add Case & Orders
    'addCase.step1': 'Clinician & Patient',
    'addCase.step2': 'Services & Guide Specs',
    'addCase.step3': 'Teeth Chart (1-32)',
    'addCase.step4': 'Scans & Internal Notes',
    'addCase.continue': 'Continue',
    'addCase.previous': 'Previous Step',
    'addCase.submit': 'Submit & Transmit Case',
    'order.overview': 'Order Overview & Clinician',
    'order.suborders': 'Sub-Orders Matrix',
    'order.viewer3d': '3D CAD / DICOM Slices Preview',
    'order.historyNotes': 'Internal History Notes',
    'profile.title': 'CP PRO MAX Specialist Profile & Workstation Settings',
    'profile.save': 'Save Preferences',
  },
  fr: {
    'brand.name': 'CP PRO MAX',
    'brand.subtitle': 'Suite 3D Diagnostix Cloud ERP & Co-Diagnostix',
    'brand.version': 'v4.2 Max Pro',
    'nav.dashboard': 'Tableau de Bord',
    'nav.flow': 'Flux des Commandes',
    'nav.addCase': 'Ajouter un Cas',
    'nav.orderDetails': 'Détails Commande',
    'nav.quarterTargets': 'Objectifs Trimestriels',
    'nav.task47': 'Tâche 47: Modèles',
    'nav.task31': 'Tâche 31: Quotas Équipe',
    'nav.editCase': 'Modifier le Cas',
    'nav.profile': 'Profil Opérateur & Paramètres',
    
    'col.serial': '# tl',
    'col.scanCenter': 'Centre de Scan tl',
    'col.doctor': 'Docteur tl',
    'col.patientName': 'Nom Patient tl',
    'col.isLocked': 'Verrouillé (?)',
    'col.notes': 'Remarques',
    'col.archiveDate': 'Date d’Archive',
    'col.more': '...',
    'col.order': 'Commande',
    'col.billTo': 'Facturer À',
    'col.max': 'Max.',
    'col.mand': 'Mand.',
    'col.format': 'Format',
    'col.amountBilled': 'Montant Facturé',
    'col.vouchers': 'Bons / Vouchers',
    'col.receivedTime': 'Heure Réception',
    'col.sentTime': 'Heure Envoi',
    'col.updateTime': 'Heure Mise à Jour',
    'col.chargedOn': 'Facturé Le',
    'col.action': 'Action',
    'col.changeRequest': 'Demande Modif.',
    'col.csTask': 'Tâche CS',

    'action.newCase': 'Nouveau Cas',
    'action.search': 'Recherche rapide...',
    'action.dockTop': 'Navbar Haut',
    'action.dockBottom': 'Barre Bas',
    'action.dockLeft': 'Barre Gauche',
    'action.dockRight': 'Barre Droite',
    'action.dragHandle': 'Glisser vers n’importe quel coin',
    'action.selectAll': 'Tout Sélectionner',
    'action.clearAll': 'Tout Effacer',
    'action.filter': 'Filtrer',
    'action.export': 'Exporter',
    'action.print': 'Imprimer Rapport',
    'action.save': 'Enregistrer',
    'action.cancel': 'Annuler',
    'action.status': 'Statut',
    'action.priority': 'Priorité',
    'action.actions': 'Actions',
    'action.view': 'Voir',
    'action.edit': 'Éditer',
    'state.normal': 'En Direct',
    'state.loading': 'Chargement',
    'state.empty': 'État Vide',
    'state.error': 'Erreur',
    'state.tester': 'Testeur d’États UI',

    'powerbi.hub': 'Analytique Power BI',
    'powerbi.cadQueue': 'File de Production CAD',
    'powerbi.refresh': 'Actualiser Métriques Power BI',
    'powerbi.targetAttainment': 'Réalisation Objectif T4',
    'powerbi.surgicalGuides': 'Guides Chirurgicaux (SG)',
    'powerbi.treatmentPlans': 'Plans de Traitement (TP)',
    'powerbi.avgTurnaround': 'Délai Moyen d’Exécution',
    'powerbi.actualRevenue': 'Revenu Réel',
    'powerbi.targetQuota': 'Quota Cible',
    'powerbi.serviceShare': 'Part par Ligne de Service',
    'powerbi.regionalHubs': 'Performance des Centres Régionaux',
    'report.quarterTargets': 'Visualiseur d’Objectifs Trimestriels 3DDX',
    'report.totalCases': 'TOTAL CAS PRODUITS',
    'report.grossRevenue': 'REVENU BRUT TRIMESTRIEL',
    'report.guidesPrinted': 'GUIDES CHIRURGICAUX IMPRIMÉS',
    'report.turnaround': 'DÉLAI MOYEN DU LABO',
    'report.targetVsAchieved': 'Production Cible vs Réalisée (T1 - T4)',
    'report.monthlyRunRate': 'Tendance Mensuelle & Enveloppe Cible',

    'teeth.upper': '+ Supérieur (1-16)',
    'teeth.lower': '+ Inférieur (17-32)',
    'teeth.smile': 'Zone du Sourire',
    'teeth.posteriors': '+ Postérieurs',
    'teeth.clearAll': 'Tout Effacer',
    'teeth.activeTool': 'Outil Actif:',
    'teeth.crown': 'Couronne',
    'teeth.bridge': 'Élément de Pont',
    'teeth.veneer': 'Facette',
    'teeth.implant': 'Implant',
    'teeth.inlay': 'Inlay / Onlay',
    'teeth.missing': 'Absent / Pontique',

    'addCase.step1': 'Praticien & Patient',
    'addCase.step2': 'Services & Spécifications Guide',
    'addCase.step3': 'Schéma Dentaire (1-32)',
    'addCase.step4': 'Scans & Notes Internes',
    'addCase.continue': 'Continuer',
    'addCase.previous': 'Étape Précédente',
    'addCase.submit': 'Soumettre et Transmettre le Cas',
    'order.overview': 'Aperçu Commande & Praticien',
    'order.suborders': 'Matrice des Sous-Commandes',
    'order.viewer3d': 'Aperçu 3D CAD / Coupes DICOM',
    'order.historyNotes': 'Historique des Notes Internes',
    'profile.title': 'Profil Spécialiste CP PRO MAX & Paramètres',
    'profile.save': 'Enregistrer Préférences',
  },
  de: {
    'brand.name': 'CP PRO MAX',
    'brand.subtitle': '3D Diagnostix Cloud ERP & Co-Diagnostix Suite',
    'brand.version': 'v4.2 Max Pro',
    'nav.dashboard': 'Dashboard',
    'nav.flow': 'Auftragsfluss',
    'nav.addCase': 'Neuer Fall',
    'nav.orderDetails': 'Auftragsdetails',
    'nav.quarterTargets': 'Quartalsziele',
    'nav.task47': 'Aufgabe 47: Modelle',
    'nav.task31': 'Aufgabe 31: Team-Quoten',
    'nav.editCase': 'Fall Bearbeiten',
    'nav.profile': 'Bedienerprofil & Einstellungen',
    
    'col.serial': '# tl',
    'col.scanCenter': 'Scan-Zentrum tl',
    'col.doctor': 'Arzt tl',
    'col.patientName': 'Patientenname tl',
    'col.isLocked': 'Gesperrt (?)',
    'col.notes': 'Notizen',
    'col.archiveDate': 'Archivdatum',
    'col.more': '...',
    'col.order': 'Auftrag',
    'col.billTo': 'Rechnung an',
    'col.max': 'Max.',
    'col.mand': 'Mand.',
    'col.format': 'Format',
    'col.amountBilled': 'Rechnungsbetrag',
    'col.vouchers': 'Gutscheine',
    'col.receivedTime': 'Eingangszeit',
    'col.sentTime': 'Sendezeit',
    'col.updateTime': 'Update-Zeit',
    'col.chargedOn': 'Abgerechnet am',
    'col.action': 'Aktion',
    'col.changeRequest': 'Änderungsantrag',
    'col.csTask': 'CS-Aufgabe',

    'action.newCase': 'Neuer Fall',
    'action.search': 'Schnellsuche...',
    'action.dockTop': 'Obere Leiste',
    'action.dockBottom': 'Untere Leiste',
    'action.dockLeft': 'Linke Leiste',
    'action.dockRight': 'Rechte Leiste',
    'action.dragHandle': 'Ziehen zum Andocken',
    'action.selectAll': 'Alles Auswählen',
    'action.clearAll': 'Alles Löschen',
    'action.filter': 'Filtern',
    'action.export': 'Exportieren',
    'action.print': 'Bericht Drucken',
    'action.save': 'Speichern',
    'action.cancel': 'Abbrechen',
    'action.status': 'Status',
    'action.priority': 'Priorität',
    'action.actions': 'Aktionen',
    'action.view': 'Ansehen',
    'action.edit': 'Bearbeiten',
    'state.normal': 'Live-Betrieb',
    'state.loading': 'Laden',
    'state.empty': 'Leer',
    'state.error': 'Fehler',
    'state.tester': 'UI-Status-Tester',

    'powerbi.hub': 'Power BI Analytik',
    'powerbi.cadQueue': 'CAD-Produktionswarteschlange',
    'powerbi.refresh': 'Power BI Metriken Aktualisieren',
    'powerbi.targetAttainment': 'Q4 Zielerreichung',
    'powerbi.surgicalGuides': 'Bohrschablonen (SG)',
    'powerbi.treatmentPlans': 'Behandlungspläne (TP)',
    'powerbi.avgTurnaround': 'Durchschnittliche Bearbeitungszeit',
    'powerbi.actualRevenue': 'Tatsächlicher Umsatz',
    'powerbi.targetQuota': 'Zielquote',
    'powerbi.serviceShare': 'Anteil nach Dienstleistung',
    'powerbi.regionalHubs': 'Regionale Scan-Zentren Leistung',
    'report.quarterTargets': '3DDX Quartalsziele & Leistungsübersicht',
    'report.totalCases': 'GESAMTE FÄLLE PRODUZIERT',
    'report.grossRevenue': 'QUARTALS-BRUTTOUMSATZ',
    'report.guidesPrinted': 'GEDRUCKTE BOHRSCHABLONEN',
    'report.turnaround': 'DURCHSCHNITTLICHE LABORDURCHLAUFZEIT',
    'report.targetVsAchieved': 'Ziel vs. Erreichte Produktion (Q1 - Q4)',
    'report.monthlyRunRate': 'Monatliche Trendlinie & Zielkorridor',

    'teeth.upper': '+ Oberkiefer (1-16)',
    'teeth.lower': '+ Unterkiefer (17-32)',
    'teeth.smile': 'Lächeln-Zone',
    'teeth.posteriors': '+ Seitenzähne',
    'teeth.clearAll': 'Alles Löschen',
    'teeth.activeTool': 'Aktives Werkzeug:',
    'teeth.crown': 'Krone',
    'teeth.bridge': 'Brückenglied',
    'teeth.veneer': 'Veneer',
    'teeth.implant': 'Implantat',
    'teeth.inlay': 'Inlay / Onlay',
    'teeth.missing': 'Fehlend / Pontik',

    'addCase.step1': 'Behandler & Patient',
    'addCase.step2': 'Dienstleistungen & Schablonenspezifikationen',
    'addCase.step3': 'Zahnschema (1-32)',
    'addCase.step4': 'Scans & Interne Notizen',
    'addCase.continue': 'Weiter',
    'addCase.previous': 'Vorheriger Schritt',
    'addCase.submit': 'Fall Übermitteln & Senden',
    'order.overview': 'Auftragsübersicht & Behandler',
    'order.suborders': 'Unterauftrags-Matrix',
    'order.viewer3d': '3D CAD / DICOM Schicht-Vorschau',
    'order.historyNotes': 'Interne Notizhistorie',
    'profile.title': 'CP PRO MAX Spezialistenprofil & Arbeitsplatzeinstellungen',
    'profile.save': 'Einstellungen Speichern',
  },
  it: {
    'brand.name': 'CP PRO MAX',
    'brand.subtitle': '3D Diagnostix Cloud ERP & Co-Diagnostix Suite',
    'brand.version': 'v4.2 Max Pro',
    'nav.dashboard': 'Dashboard',
    'nav.flow': 'Flusso Ordini',
    'nav.addCase': 'Nuovo Caso',
    'nav.orderDetails': 'Dettagli Ordine',
    'nav.quarterTargets': 'Obiettivi Trimestrali',
    'nav.task47': 'Task 47: Modelli',
    'nav.task31': 'Task 31: Quote Staff',
    'nav.editCase': 'Modifica Caso',
    'nav.profile': 'Profilo Operatore & Impostazioni',
    
    'col.serial': '# tl',
    'col.scanCenter': 'Centro Scansione tl',
    'col.doctor': 'Dottore tl',
    'col.patientName': 'Nome Paziente tl',
    'col.isLocked': 'Bloccato (?)',
    'col.notes': 'Note',
    'col.archiveDate': 'Data Archivio',
    'col.more': '...',
    'col.order': 'Ordine',
    'col.billTo': 'Fattura A',
    'col.max': 'Max.',
    'col.mand': 'Mand.',
    'col.format': 'Formato',
    'col.amountBilled': 'Importo Fatturato',
    'col.vouchers': 'Voucher',
    'col.receivedTime': 'Ora Ricezione',
    'col.sentTime': 'Ora Invio',
    'col.updateTime': 'Ora Aggiornamento',
    'col.chargedOn': 'Addebitato Il',
    'col.action': 'Azione',
    'col.changeRequest': 'Richiesta Modifica',
    'col.csTask': 'Task CS',

    'action.newCase': 'Nuovo Caso',
    'action.search': 'Ricerca rapida...',
    'action.dockTop': 'Barra Superiore',
    'action.dockBottom': 'Barra Inferiore',
    'action.dockLeft': 'Barra Sinistra',
    'action.dockRight': 'Barra Destra',
    'action.dragHandle': 'Trascina per ancorare',
    'action.selectAll': 'Seleziona Tutto',
    'action.clearAll': 'Cancella Tutto',
    'action.filter': 'Filtra',
    'action.export': 'Esporta',
    'action.print': 'Stampa Report',
    'action.save': 'Salva Modifiche',
    'action.cancel': 'Annulla',
    'action.status': 'Stato',
    'action.priority': 'Priorità',
    'action.actions': 'Azioni',
    'action.view': 'Visualizza',
    'action.edit': 'Modifica',
    'state.normal': 'Live Normale',
    'state.loading': 'Caricamento',
    'state.empty': 'Vuoto',
    'state.error': 'Errore',
    'state.tester': 'Tester Stati UI',

    'powerbi.hub': 'Analitica Power BI',
    'powerbi.cadQueue': 'Coda Produzione CAD',
    'powerbi.refresh': 'Aggiorna Metriche Power BI',
    'powerbi.targetAttainment': 'Raggiungimento Target Q4',
    'powerbi.surgicalGuides': 'Guide Chirurgiche (SG)',
    'powerbi.treatmentPlans': 'Piani di Trattamento (TP)',
    'powerbi.avgTurnaround': 'Tempo Medio di Consegna',
    'powerbi.actualRevenue': 'Ricavi Effettivi',
    'powerbi.targetQuota': 'Quota Target',
    'powerbi.serviceShare': 'Quota per Linea di Servizio',
    'powerbi.regionalHubs': 'Rendimento Centri Regionali',
    'report.quarterTargets': 'Visualizzatore Obiettivi Trimestrali 3DDX',
    'report.totalCases': 'TOTALE CASI PRODOTTI',
    'report.grossRevenue': 'RICAVI LORDI TRIMESTRALI',
    'report.guidesPrinted': 'GUIDE CHIRURGICHE STAMPATE',
    'report.turnaround': 'TEMPO MEDIO DI LABORATORIO',
    'report.targetVsAchieved': 'Produzione Obiettivo vs Raggiunta (Q1 - Q4)',
    'report.monthlyRunRate': 'Andamento Mensile & Curva Obiettivo',

    'teeth.upper': '+ Superiore (1-16)',
    'teeth.lower': '+ Inferiore (17-32)',
    'teeth.smile': 'Zona del Sorriso',
    'teeth.posteriors': '+ Posteriori',
    'teeth.clearAll': 'Cancella Tutto',
    'teeth.activeTool': 'Strumento Attivo:',
    'teeth.crown': 'Corona',
    'teeth.bridge': 'Elemento Ponte',
    'teeth.veneer': 'Faccetta',
    'teeth.implant': 'Impianto',
    'teeth.inlay': 'Inlay / Onlay',
    'teeth.missing': 'Mancante / Elemento',

    'addCase.step1': 'Clinico & Paziente',
    'addCase.step2': 'Servizi & Specifiche Guida',
    'addCase.step3': 'Odontogramma (1-32)',
    'addCase.step4': 'Scansioni & Note Interne',
    'addCase.continue': 'Continua',
    'addCase.previous': 'Passo Precedente',
    'addCase.submit': 'Invia e Trasmetti Caso',
    'order.overview': 'Panoramica Ordine & Clinico',
    'order.suborders': 'Matrice Sotto-Ordini',
    'order.viewer3d': 'Anteprima 3D CAD / Fette DICOM',
    'order.historyNotes': 'Cronologia Note Interne',
    'profile.title': 'Profilo Specialista CP PRO MAX & Impostazioni',
    'profile.save': 'Salva Preferenze',
  },
  es: {
    'brand.name': 'CP PRO MAX',
    'brand.subtitle': '3D Diagnostix Cloud ERP & Co-Diagnostix Suite',
    'brand.version': 'v4.2 Max Pro',
    'nav.dashboard': 'Panel de Control',
    'nav.flow': 'Flujo de Órdenes',
    'nav.addCase': 'Agregar Caso',
    'nav.orderDetails': 'Detalles de Orden',
    'nav.quarterTargets': 'Objetivos Trimestrales',
    'nav.task47': 'Tarea 47: Modelos',
    'nav.task31': 'Tarea 31: Metas Equipo',
    'nav.editCase': 'Editar Caso',
    'nav.profile': 'Perfil de Operador y Ajustes',
    
    'col.serial': '# tl',
    'col.scanCenter': 'Centro de Escaneo tl',
    'col.doctor': 'Doctor tl',
    'col.patientName': 'Nombre Paciente tl',
    'col.isLocked': 'Bloqueado (?)',
    'col.notes': 'Notas',
    'col.archiveDate': 'Fecha Archivo',
    'col.more': '...',
    'col.order': 'Orden',
    'col.billTo': 'Facturar A',
    'col.max': 'Max.',
    'col.mand': 'Mand.',
    'col.format': 'Formato',
    'col.amountBilled': 'Monto Facturado',
    'col.vouchers': 'Vales',
    'col.receivedTime': 'Hora Recepción',
    'col.sentTime': 'Hora Envío',
    'col.updateTime': 'Hora Actualización',
    'col.chargedOn': 'Cobrado El',
    'col.action': 'Acción',
    'col.changeRequest': 'Solicitud Cambio',
    'col.csTask': 'Tarea CS',

    'action.newCase': 'Nuevo Caso',
    'action.search': 'Búsqueda rápida...',
    'action.dockTop': 'Barra Superior',
    'action.dockBottom': 'Barra Inferior',
    'action.dockLeft': 'Barra Izquierda',
    'action.dockRight': 'Barra Derecha',
    'action.dragHandle': 'Arrastrar para acoplar en cualquier borde',
    'action.selectAll': 'Seleccionar Todo',
    'action.clearAll': 'Limpiar Todo',
    'action.filter': 'Filtrar',
    'action.export': 'Exportar',
    'action.print': 'Imprimir Reporte',
    'action.save': 'Guardar Cambios',
    'action.cancel': 'Cancelar',
    'action.status': 'Estado',
    'action.priority': 'Prioridad',
    'action.actions': 'Acciones',
    'action.view': 'Ver',
    'action.edit': 'Editar',
    'state.normal': 'En Vivo',
    'state.loading': 'Cargando',
    'state.empty': 'Sin Registros',
    'state.error': 'Error',
    'state.tester': 'Probador Estados UI',

    'powerbi.hub': 'Analítica Power BI',
    'powerbi.cadQueue': 'Cola de Producción CAD',
    'powerbi.refresh': 'Actualizar Métricas Power BI',
    'powerbi.targetAttainment': 'Cumplimiento Meta T4',
    'powerbi.surgicalGuides': 'Guías Quirúrgicas (SG)',
    'powerbi.treatmentPlans': 'Planes de Tratamiento (TP)',
    'powerbi.avgTurnaround': 'Tiempo Medio de Entrega',
    'powerbi.actualRevenue': 'Ingresos Reales',
    'powerbi.targetQuota': 'Cuota Objetivo',
    'powerbi.serviceShare': 'Participación por Servicio',
    'powerbi.regionalHubs': 'Rendimiento Centros Regionales',
    'report.quarterTargets': 'Visor de Metas Trimestrales 3DDX',
    'report.totalCases': 'TOTAL CASOS PRODUCIDOS',
    'report.grossRevenue': 'INGRESOS BRUTOS TRIMESTRALES',
    'report.guidesPrinted': 'GUÍAS QUIRÚRGICAS IMPRESAS',
    'report.turnaround': 'TIEMPO MEDIO DE LABORATORIO',
    'report.targetVsAchieved': 'Producción Meta vs Alcanzada (T1 - T4)',
    'report.monthlyRunRate': 'Tendencia Mensual y Envolvente Objetivo',

    'teeth.upper': '+ Superior (1-16)',
    'teeth.lower': '+ Inferior (17-32)',
    'teeth.smile': 'Zona de Sonrisa',
    'teeth.posteriors': '+ Posteriores',
    'teeth.clearAll': 'Limpiar Todo',
    'teeth.activeTool': 'Herramienta Activa:',
    'teeth.crown': 'Corona',
    'teeth.bridge': 'Unidad de Puente',
    'teeth.veneer': 'Carilla',
    'teeth.implant': 'Implante',
    'teeth.inlay': 'Inlay / Onlay',
    'teeth.missing': 'Ausente / Póntico',

    'addCase.step1': 'Médico y Paciente',
    'addCase.step2': 'Servicios y Especificaciones Guía',
    'addCase.step3': 'Odontograma (1-32)',
    'addCase.step4': 'Escaneos y Notas Internas',
    'addCase.continue': 'Continuar',
    'addCase.previous': 'Paso Anterior',
    'addCase.submit': 'Enviar y Transmitir Caso',
    'order.overview': 'Resumen de Orden y Clínico',
    'order.suborders': 'Matriz de Sub-Órdenes',
    'order.viewer3d': 'Vista 3D CAD / Cortes DICOM',
    'order.historyNotes': 'Historial de Notas Internas',
    'profile.title': 'Perfil de Especialista CP PRO MAX y Ajustes',
    'profile.save': 'Guardar Preferencias',
  },
};

const currentLang = ref<LanguageCode>(
  (localStorage.getItem('3ddx-cp-language') as LanguageCode) || 'en'
);

export function useLanguage() {
  const setLanguage = (code: LanguageCode) => {
    currentLang.value = code;
    localStorage.setItem('3ddx-cp-language', code);
    document.documentElement.lang = code;
  };

  const currentOption = computed(() => {
    return LANGUAGES.find((l) => l.code === currentLang.value) || LANGUAGES[0];
  });

  const t = (key: string, fallback?: string): string => {
    const dict = TRANSLATIONS[currentLang.value] || TRANSLATIONS.en;
    if (dict && dict[key]) return dict[key];
    const enDict = TRANSLATIONS.en;
    if (enDict && enDict[key]) return enDict[key];
    return fallback || key;
  };

  return {
    language: currentLang,
    setLanguage,
    currentOption,
    t,
    languages: LANGUAGES
  };
}
